### ISSUE TITLE
Android build error:  no suitable constructor found for Stripe(no arguments)

### ISSUE THREAD

**Issue by mwiley63** [zyramedia/cordova-plugin-stripe#9]
I installed this plugin today and ran into an error when building my cordova application for Android.

```
platforms/android/src/com/zyramedia/cordova/stripe/CordovaStripe.java:24: error: no suitable constructor found for Stripe(no arguments)
```

I notice this error occurs with the Java Stripe SDK v3.0 and 3.1 (both updated in the past 3 days).  

As a workaround I can modify `platforms/android/cordova-plugin-stripe/appname-CordovaStripe.gradle` to specify version 2.1.0:
```
dependencies {
    compile 'com.stripe:stripe-android:2.1.0'
}
```
And the build passes.  However this is not ideal as this code is generated.  Is there a better workaround or will I need to wait for a patch?

Thanks!

**Comment by ihadeed** [comment]
Yes for now you need to specify the version. It's fixed in the repo but not in the latest npm version. (you can install the plugin directly from the repository instead of npm)

I will update the code to work with their 3.0.0 SDK in the next week or so, and that should fix the problem for sure.
